name: CIGradingTest
on:
  workflow_call:
  # push:
  #   branches:
  #   - main

jobs:
  ci-test:
    runs-on: ubuntu-latest
    container: haskell:9.0-slim   
    steps:
      - uses: actions/checkout@v3
      # - name: Download test runner
      #   run: curl -o ${GITHUB_WORKSPACE}/run https://github.com/trungIsOnGithhub/CIgradingTest/raw/main/run
      - run: echo $GITHUB_WORKSPACE
      # - run: chmod +x /${GITHUB_WORKSPACE}/run && /${GITHUB_WORKSPACE}/run
      # - run: echo https://github.com/trungIsOnGithhub/CIgradingTest/raw/main/run/${CALLER_KEY}
      # - run: ls ${GITHUB_WORKSPACE}
      - run: ls ${GITHUB_WORKSPACE}/app
      # - run: echo ${{github.actor}}
      - run: echo ${{ github }}
      - name: Download Haskell driver code
        run: curl -o ./app/Main.hs https://raw.githubusercontent.com/trungIsOnGithhub/CIgradingTest/main/Main.hs
      # - name: Download script run test
      #   run: curl -o ./app/run.sh https://raw.githubusercontent.com/trungIsOnGithhub/CIgradingTest/main/run.sh
      # - name: Test if test generator exist in main workspace
      #   run: ls ${GITHUB_WORKSPACE}/app
      # - run: cat ./app/Main.hs
      # - name: Give permission to script test file
      #   run: chmod +x ./app/run
      # - name: Run test generator
      #   run: ./app/run
      # - run: mv ./tests ./app/tests
      # - name: Pre-Run test if test generator exist in main workspace
      #   run: ls ./app
      - name: Run test officially
        run: cabal run -v0
      - run: ls ${GITHUB_WORKSPACE}/app
      # - run: cat ${GITHUB_WORKSPACE}/app/out
      - run: cat ${GITHUB_WORKSPACE}/out1
      - run: cat ${GITHUB_WORKSPACE}/out2
      # - run: cd .. && ls
      # - run: cd .. && cd .. && ls
      # - run: cd .. && cd .. && cd .. && ls
      # - run: cd / && ls
      # - run: find / -name cnpmnc.cabal
      # - run: cd /tmp && ls
      # - run: cd /github/home && ls
      # - run: ls
      # - run: cabal --version
      # - run: ./test
      # - run: cabal update -v0
      # - run: ./app/run
      # - run: cabal run -v0
      # - run: ghc hello.hs
      # - run: ./hello
      # - run: apt-get update
      # - run: apt-get -qq install lsof python3.11 python3-selenium
      # - run: npm i
      # - run: node server.js &
      # - run: npm run test
      # - run: cd __test__/testUI/
      # - run: python3 script.py
      # - run: kill -9 $(lsof -t -i:5000)
  # pytest:
  #   runs-on: ubuntu-latest
  #   container: nikolaik/python-nodejs:python3.11-nodejs18-alpine
  #   steps:
  #     - run: apt-get update
  #     - run: apt-get -qq install lsof
  #     - run: node server.js &
      
  #     - run: kill -9 $(lsof -t -i:5000)