name: CIGradingTest
on:
  workflow_call:
  # push:
  #   branches:
  #   - main

jobs:
  ci-test:
    runs-on: ubuntu-latest
    container:
      image: haskell:9.0-slim    
    steps:
      - uses: actions/checkout@v3
        with:
          path: '/usr'
      - run: bash ./run.sh
      - run: echo $GITHUB_WORKSPACE
      - run: gcc --version
      # - run: cd .. && ls
      # - run: cd .. && cd .. && ls
      # - run: cd .. && cd .. && cd .. && ls
      # - run: cd / && ls
      # - run: find / -name cnpmnc.cabal
      # - run: cd /tmp && ls
      # - run: cd /github/home && ls
      # - run: ls
      # - run: cabal --version
      # - run: ./test
      # - run: cabal update -v0
      - run: ./app/run
      - run: cabal run -v0
      # - run: ghc hello.hs
      # - run: ./hello
      # - run: apt-get update
      # - run: apt-get -qq install lsof python3.11 python3-selenium
      # - run: npm i
      # - run: node server.js &
      # - run: npm run test
      # - run: cd __test__/testUI/
      # - run: python3 script.py
      # - run: kill -9 $(lsof -t -i:5000)
  # pytest:
  #   runs-on: ubuntu-latest
  #   container: nikolaik/python-nodejs:python3.11-nodejs18-alpine
  #   steps:
  #     - run: apt-get update
  #     - run: apt-get -qq install lsof
  #     - run: node server.js &
      
  #     - run: kill -9 $(lsof -t -i:5000)